### ISSUE TITLE
【依頼】フリマアプリの挙動確認

### ISSUE THREAD

**Issue by tech-kannnari** [tech-kannnari/furima-34414#10]
アプリのURL：https://furima-34414.herokuapp.com/

Basic認証のID：furima
　  パスワード：0000

出品者用のメールアドレス：p@p
　　　　　　　パスワード：000000o

購入者用のメールアドレス：o@o
　　　　　　　パスワード：000000o

よろしくお願い致します！！

**Comment by snkw-works** [comment]
@tech-kannnari さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品購入ページへ遷移しようとすると、トップページに遷移するよう修正しましょう**
- [x] **購入した商品は、再度購入できない状態になるよう修正しましょう**
現状、ログイン状態のユーザーが、URLを直接入力すると売却済み商品の商品購入ページへ遷移できてしまいます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by tech-kannnari** [comment]
動作確認をしていただきありがとうございます！
修正が完了しましたので、再度ご確認をお願い致します！

**Comment by snkw-works** [comment]
@tech-kannnari さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/111092621-dff75f00-8579-11eb-804a-2818ed069d9d.png)

**Comment by tech-kannnari** [comment]
レビューをしていただき、ありがとうございます！
最終課題のLGTMはもらえたことで、プログラミング学習のスタートラインに立てたような気持ちです！
これからも頑張っていきたいと思います！！
